name: taller_rodriguez_backend
version: 1.0.0

environment:
  sdk: ^3.11.1

dependencies:

  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http: ^0.13.6
  get_it: ^7.7.0
  equatable: ^2.0.5
  supabase_flutter: ^2.0.0

dev_dependencies: {}

executables:
  server:
    entry: bin/server.dart